import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#15202B] text-white`}>
          <div className='grid grid-cols-10 divide-x divide-gray-700 h-screen w-full'>
            <div className='max-sm:hidden sm:block xl:col-span-2 2xl:col-span-3 col-span-1'>
              <Navbar />
            </div>
            <div className='sm:col-span-8 2xl:col-span-7 max-sm:col-span-10'>
              {children}
            </div>
          </div>
      </body>
    </html>
  )
}
